jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: echo "This is a build step"    # similar to "script" in GitLab

  test:
    machine: true
    steps:
      - checkout
      - run: echo "This is a test step"

  chelsea:
    machine: true
    steps:
      - checkout

      - run:
          name: Run chelsea
          command: |
            gem install chelsea
            chelsea -f Gemfile.lock -t json | tail -n1 > chelsea-output.json      # tail -n1 to remove chelsea banner
          when: always
          
      - store_artifacts:
          path: chelsea-output.json
          destination: chelsea-artifact
          when: always

  bundler-audit:
    machine: true
    steps:
      - checkout

      - run: 
          name: Run bundler-audit
          command: docker run --rm -v $(pwd):/src -w /src hysnsec/bundle-audit check --format json --output bundle-audit-output.json
          when: always

      - store_artifacts:
          path: bundle-audit-output.json
          destination: bundler-audit-artifact
          when: always

  integration:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run:
          command: |
            echo "This is an integration step"
            exit 1

  prod:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run: echo "This is a deploy step."

workflows:
  version: 2
  rails:
    jobs:
      - build
      - test:
          requires:
            - build
      - chelsea:
          requires:
            - test
      - bundler-audit:
          requires:
            - test 
      - integration:
          requires:
            - bundler-audit
      - prod:
          type: approval
          requires:
            - integration
